### ISSUE TITLE
Does it work with Master Detail pages ?

### ISSUE THREAD

**Issue by jcaffera** [GiampaoloGabba/Xamarin.Plugin.SharedTransitions#21]
## Bug Information

Version Number of Plugin: 2.0.2
Simulator Tested On: Android 7.1
Version of VS: 16.4.3
Version of Xamarin: 3.6.0.709228
Prism.DryIoc.Forms 7.2.0.1422

### Steps to reproduce the Behavior
While using Prism, if I navigate to "/MasterDetailPage/SharedTransitionNavigationPage/SomePage",  and then transition to another page using NavigationService.NavigateTo("SomeOtherPage"), the shared transitions between SomePage and SomeOtherPage won't work. However, they work if I navigate to "/SharedTransitionNavigationPage/SomePage" and then call NavigationService.NavigateTo("SomeOtherPage").

Can you tell if I'm doing something wrong, or missing a step to make it work? 
Thanks

**Comment by naweed** [comment]
Hi,
I have the exact same issue. If I use MasterDetailPage in Prism, the shared transitions don't work, but without MasterDetailPage, it works perfectly fine. Any solution to this? This is my code in App.xaml.cs:

//Shared Tansitions don't work if wrapped in Master Details Page:
await NavigationService.NavigateAsync($"{nameof(MasterDetailShellPage)}/{nameof(SharedTransitionNavigationPage)}/{nameof(DiscoverPage)}");

//This works:
await NavigationService.NavigateAsync($"{nameof(SharedTransitionNavigationPage)}/{nameof(DiscoverPage)}");

In DiscoverPageViewModel, I am Navigating to another page which has the target transition.

Thanks

**Comment by GiampaoloGabba** [comment]
Uhm.. i tried the masterdetail only on shell (in the relative branch) and it works.

But maybe i found the culprit: when using the transition effect on an element i have to traverse the view hierarchy to find the SharedTransitionNavigationPage to connect the transition.
When using a MasterPage the traverse doesnt go well, i'm planning a fix for this in the new version that will support AndroidX and Shell.

**Comment by GiampaoloGabba** [comment]
Hello, this is fixed in the next version coming very soon!

**Comment by mhrastegary77** [comment]
hi, how it works with Master Detail page Template ?
i updated but the result is the same!  :(

**Comment by Strypper** [comment]
Hello did you say you tried it on the shell ? I tried it too but it keep entering break mode
![image](https://user-images.githubusercontent.com/32596308/85205901-8cd4e080-b348-11ea-9f0e-9abb3c40a4f3.png)

**Comment by mhrastegari** [comment]
And i still cannot/dunno how to use it for master detail template!

**Comment by GiampaoloGabba** [comment]
> Hello did you say you tried it on the shell ? I tried it too but it keep entering break mode
> ![image](https://user-images.githubusercontent.com/32596308/85205901-8cd4e080-b348-11ea-9f0e-9abb3c40a4f3.png)

Hello, in order to use Shared Transitions with shell you have to use `SharedTransitionShell`.

Something like this (replacing the Tabs witth your ShellContent):
```
<sharedTransitions:SharedTransitionShell xmlns="http://xamarin.com/schemas/2014/forms" 
       xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"

[Here you can find an example using shell](https://github.com/GiampaoloGabba/Xamarin.Plugin.SharedTransitions/tree/master/src/Sample/TransitionShellApp/TransitionShellApp). It use tabs but should be trivial to modify it to make it work with the Flyout
       xmlns:sharedTransitions="clr-namespace:Plugin.SharedTransitions;assembly=Plugin.SharedTransitions"
       Title="TransitionShellApp"
       x:Class="TransitionShellApp.AppShell">

    <!-- Your Pages -->
    <TabBar>
        ....
    </TabBar>
</sharedTransitions:SharedTransitionShell>
```
You can not use a `SharedTransitionNavigationPage` inside a Shell

**Comment by GiampaoloGabba** [comment]
> And i still cannot/dunno how to use it for master detail template!

Hello, in the sample app there is a full example of shared transitions inside a MasterDetailPage, [ you can find it here](https://github.com/GiampaoloGabba/Xamarin.Plugin.SharedTransitions/blob/master/src/Sample/TransitionApp/TransitionApp/Views/Main/MainMasterDetailPage.xaml)

**Comment by mhrastegari** [comment]
Hi, i think i missed something here, can you help me? i saw that sample but still crashing :(

![Snapshot_20-06-23_00-14-53](https://user-images.githubusercontent.com/42671084/85328911-d0fde780-b4e6-11ea-96b6-b8471e8d7f14.png)
